// Zentrale Icon-Definitionen für optimale Tree-Shaking
import {
  mdiHome,
  mdiAccount,
  mdiCodeTags,
  mdiDatabaseSearch,
  mdiCertificate,
  mdiSchool,
  mdiWeatherSunny,
  mdiWeatherNight,
  mdiMagnify,
  mdiInformationOutline,
  mdiLanguagePython,
  mdiLanguageJavascript,
  mdiLanguageTypescript,
  mdiLanguageHtml5,
  mdiLanguageCss3,
  mdiLanguagePhp,
  mdiVuejs,
  mdiVuetify,
  mdiGit,
  mdiDatabase,
  mdiLanguageJava,
  mdiNodejs,
  mdiChip,
  mdiBrain,
  mdiCalendar,
  mdiTranslate,
  mdiClockOutline,
  mdiConsole,
  mdiFileChart,
  mdiApplicationBrackets,
  mdiApplicationOutline,
  mdiPowershell,
  mdiIpNetwork,
  mdiJira,
  mdiLayers,
  mdiRobot,
  mdiRobotOutline,
  mdiRobotAngry,
  mdiReact,
  mdiFloorPlan,
  mdiServerNetwork,
  mdiBootstrap,
  mdiFlask,
  mdiGithub,
  mdiBitbucket,
  mdiBookOpenPageVariant,
  mdiApi,
  mdiMicrosoftVisualStudioCode,
  mdiLaptop,
  mdiAlphaJBox,
  mdiEmoticonHappyOutline,
  mdiShieldCheck,
  mdiLinkVariant,
  mdiWeb,
  mdiRunFast,
  mdiFlash,
  mdiCheckCircle,
  mdiDocker,
  mdiDesktopTower,
  mdiMicrosoftWindows,
  mdiUbuntu,
  mdiFileWord,
  mdiFileExcel,
  mdiFilePowerpoint,
  mdiMicrosoftTeams,
  mdiFileDocumentMultiple,
  mdiPalette,
} from '@mdi/js'

export const icons = {
  home: mdiHome,
  account: mdiAccount,
  codeTags: mdiCodeTags,
  databaseSearch: mdiDatabaseSearch,
  certificate: mdiCertificate,
  school: mdiSchool,
  weatherSunny: mdiWeatherSunny,
  weatherNight: mdiWeatherNight,
  magnify: mdiMagnify,
  informationOutline: mdiInformationOutline,
  languagePython: mdiLanguagePython,
  languageJavascript: mdiLanguageJavascript,
  languageTypescript: mdiLanguageTypescript,
  languageHtml5: mdiLanguageHtml5,
  languageCss3: mdiLanguageCss3,
  languagePhp: mdiLanguagePhp,
  vuejs: mdiVuejs,
  vuetify: mdiVuetify,
  git: mdiGit,
  database: mdiDatabase,
  languageJava: mdiLanguageJava,
  nodejs: mdiNodejs,
  chip: mdiChip,
  brain: mdiBrain,
  calendar: mdiCalendar,
  translate: mdiTranslate,
  clockOutline: mdiClockOutline,
  console: mdiConsole,
  fileChart: mdiFileChart,
  applicationBrackets: mdiApplicationBrackets,
  applicationOutline: mdiApplicationOutline,
  powershell: mdiPowershell,
  ipNetwork: mdiIpNetwork,
  jira: mdiJira,
  layers: mdiLayers,
  robot: mdiRobot,
  robotOutline: mdiRobotOutline,
  robotAngry: mdiRobotAngry,
  react: mdiReact,
  floorPlan: mdiFloorPlan,
  serverNetwork: mdiServerNetwork,
  bootstrap: mdiBootstrap,
  flask: mdiFlask,
  github: mdiGithub,
  bitbucket: mdiBitbucket,
  bookOpenPageVariant: mdiBookOpenPageVariant,
  api: mdiApi,
  microsoftVisualStudioCode: mdiMicrosoftVisualStudioCode,
  laptop: mdiLaptop,
  alphaJBox: mdiAlphaJBox,
  emoticonHappyOutline: mdiEmoticonHappyOutline,
  shieldCheck: mdiShieldCheck,
  linkVariant: mdiLinkVariant,
  web: mdiWeb,
  runFast: mdiRunFast,
  flash: mdiFlash,
  checkCircle: mdiCheckCircle,
  docker: mdiDocker,
  desktopTower: mdiDesktopTower,
  microsoftWindows: mdiMicrosoftWindows,
  ubuntu: mdiUbuntu,
  fileWord: mdiFileWord,
  fileExcel: mdiFileExcel,
  filePowerpoint: mdiFilePowerpoint,
  microsoftTeams: mdiMicrosoftTeams,
  fileDocumentMultiple: mdiFileDocumentMultiple,
  palette: mdiPalette,
}
